apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: mrgromovvitaly/hipster_front:1
    name: frontend
    resources: {}
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:8500"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:8501"
      - name: CART_SERVICE_ADDR
        value: "cartservice:8502"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8503"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:8504"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:8505"
      - name: AD_SERVICE_ADDR
        value: "adservice:8506"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}